kind: pipeline
name: default

steps:
  - name: checkout
    image: alpine/git
    commands:
      - git clone https://github.com/manalsaqib/testing-git-.git /drone/src  # Replace with your repository URL
      - cd /drone/src  # Change the working directory to your project root

  - name: install_dependencies 
  - name: build
